name: gzx_dropdown_menu_example
description: Demonstrates how to use the gzx_dropdown_menu plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#Dart 运行环境区间
environment:
  #  sdk: ">=2.11.0 <3.0.0" # Dart SDK版本号，多人开发建议写死
  # 健全的空安全已在 Dart 2.12 和 Flutter 2 中可用。
  # 所以迁移到空安全的
  # 第一步：升级Flutter到2.0
  # 第二步：修改Dart SDK范围为2.12.x以上
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 你可以通过以下三种方式引入gzx_dropdown_menu

  # 方式1：使用语义版本控制（推荐使用）
  # ^3.1.5 等于 '>=3.1.5 <4.0.0'
  # ^1.2.3 等于 '>=1.2.3 <2.0.0'
  # ^0.1.2 等于 '>=0.1.2 <0.2.0'
  # see detail https://stackoverflow.com/questions/53563079/what-is-the-caret-sign-before-the-dependency-version-number-in-flutters-pub
  #  gzx_dropdown_menu : ^2.1.0

  # 方式2：通过远程Git仓库
  #  gzx_dropdown_menu :
  #   git:
  #     url: https://github.com/GanZhiXiong/gzx_dropdown_menu.git

  # 方式3：通过本地路径
  gzx_dropdown_menu:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
